<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageId>SoPro.FancyTable</PackageId>
    <Version>1.0.6</Version>
    <Authors>SolidProgramming</Authors>
    <Description>Reusable Blazor table components with sorting, search, column visibility, and tree table support.</Description>
    <PackageTags>blazor;table;tree-table;razor;components</PackageTags>
	<RepositoryUrl>https://github.com/SolidProgramming/SoPro.FancyTable</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
	<PackageProjectUrl>https://github.com/SolidProgramming/SoPro.FancyTable</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include=".github\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
